spring:
  # 前端支持热重载
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://173.82.212.76:3306/mysite
    username: root
    password: root
  devtools:
    restart:
      enabled: true
      # 热重载排除目录
      additional-exclude: /static/**,/templates/**
# mybatis 配置
#mybatis:
#  type-aliases-package: com.liunan.readinglist.entity
#  mapper-locations: classpath:mapper/*.xml
