server:
  port: 8888
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eurka.instance.hostname}:${eurka.port}/eureka
  server:
#    enable-self-preservation: false